### ISSUE TITLE
More informative error if resource have connection problems

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-csi#15]
When drbd-resource have connection issues, eg. when diskless replica have no connection to data-replocas, csi-driver reports:

```
rpc error: code = Unknown desc = couldn't create ext4 filesystem on /dev/drbd1055: exit status 1: "mke2fs 1.42.13 (17-May-2015)\nCould not open /dev/drbd1055: Wrong medium type\n"
```

This is totally confusing, It would be nice to see more suitable error in this case, instead `couldn't create ext4 filesystem`

**Comment by haySwim** [comment]
This is tricky because that `Could not open /dev/drbd1055: Wrong medium type\n` is _I think_ reported to `mkfs` by DRBD and beyond trying to create a filesystem and reporting an error. I'm not sure what kind of diagnostic information is available besides the provided path is a block device on the given node and we already do that here.

Trickier still: this is a DRBD-specific error. The function that's reporting this only knows about writing out filesystems and a semi-sane way. @raltnoeder is there a layer-list agnostic way to check for the health of a resource on a particular node that would catch this?

I suppose we could inspect the error string for `Wrong medium type` or look at `drbdsetup events2`, but both are more hackish than I would prefer.

**Comment by raltnoeder** [comment]
There is currently no way of asking the system whether or not a particular volumes is actually readable/writable. Also, the Linux kernel has no notion of active/passive mode volumes, so if a volume does not work because it is not in an active mode (e.g. Primary), or cannot enter active mode because of some problem (e.g., no connection), then all the DRBD driver can do is to report "wrong media type", because there is no meaningful error code for such a condition in the system.

The only check I could think of would be to check the resource's status using the drbdsetup events2 stream to maybe figure out why a volume might not work, but obviously the states reported on the events stream can race with the actual error.

**Comment by rck** [comment]
I think the "confusing" part for people is that they don't even know that we have to create a file system on top of the DRBD device to make it usable. That is why kvaps referred to the "mkfs" part of the error message. People without knowing how their underlying technology actually works - a problem on its own - assume a (DRBD) block device "just works". And then they are confused where the "mkfs" actually comes from.

Maybe we could try to `mkfs` and if it fails prefix the error with some "could not prepare the DRBD volume for actual use, and this is why: %v". Guess that would help to make it less "confusing" than just seeing the plain mkfs error without context why there was a mkfs in the first place.

**Comment by kvaps** [comment]
@rck, no, confusing part is that when you have pod with the volume which is created and working fine about few weeks already, and then you're try to recreate the pod on another node and see this mkfs error on same volume.

Untrained person can have stand on end hair after seen these message and anticipating possible data loss :)

**Comment by rck** [comment]
I see, thanks for clarifying this.

**Comment by haySwim** [comment]
> @raltnoeder I presume because [this check](https://github.com/LINBIT/golinstor/blob/3455ca3e0ab482722dd2952df048e57460a124f6/linstor.go#L1086) is not enough for make sure that block device is conneted and not containing any filesystem.

There problem there is, according to the comments there is an error thrown when there's no filesystem on the block device, rather than just blank output.

> Now I am confused: Why is a volume that contains data (aka "has been in use for weeks") being formatted anyway?

NodeStageVolume, like pretty much every CSI call, must be idempotent. CSI inspects it to see it if has been formatted with the the appropriate filesystem every time before it's mounted. Unfortunately, a disconnected drbd device and an unformatted block device aren't distinguishable with our checks now.

> Judging by the error message, some other component formats the volume, not LINSTOR. Recent versions of LINSTOR are able to format devices, but the error posted here does not seem to originate from LINSTOR, but rather from either the driver or some other task.

Yeah, this particular section is a port of DRBD Manage adjacent code.

Right now, there are plans to move the in-tree k8s mounting and FS stuff outside of k8s into it's own repository with the expectation that CSI drivers will use them. The plan has been to switch to that, so we have more uniformity of functionality with other CSI drivers.

I'll take a look at the mount util there and see if that will encounter a similar issue.

**Comment by raltnoeder** [comment]
Got it.
I think a simple fix would be to `os.Open(dev)` and if that fails, to return an error from `checkFsType(...)`, so that the call in line 1033 in `SafeFormat(...)` takes the error branch. Line 1035 should probably read something like _"unable to read device ..."_ instead of _"unable to format filesystem for ..."_, because the decision to format has not been made yet.
That should clarify the case where the device is inoperative because it is diskless and disconnected.

**Comment by haySwim** [comment]
I like the `os.Open` idea, probably we can do that as a guard clause before `SafeFormat` and not have to worry about changing `SafeFormat`s current behavior, which works well for devices that it actually can open.
